// ============================================================
// BİLGİ DÜELLOSU — Soru İçerikleri
// Şimdilik her şey "kolay" seviyesinde. İleride her soruya
// difficulty: 'kolay' | 'orta' | 'zor' alanı eklenecek.
// ============================================================

const DATA = {

  // ---------- KATEGORİ 1: BAYRAKLAR ----------
  // Bu bayrak hangi ülkenin? (4 şıklı)
  bayrak: [
    { flag: '🇹🇷', answer: 'Türkiye', wrong: ['Tunus', 'Cezayir', 'Fas'], fact: 'Ay-yıldız motifi Osmanlı döneminden beri kullanılıyor; bayrak 1936\'da kanunla bugünkü halini aldı.' },
    { flag: '🇯🇵', answer: 'Japonya', wrong: ['Çin', 'Güney Kore', 'Vietnam'], fact: 'Kırmızı daire güneşi simgeler; Japonya\'ya "Güneşin Doğduğu Ülke" denir.' },
    { flag: '🇫🇷', answer: 'Fransa', wrong: ['Hollanda', 'Rusya', 'Lüksemburg'], fact: 'Mavi-beyaz-kırmızı üç renk, 1789 Fransız Devrimi\'nin "özgürlük, eşitlik, kardeşlik" değerlerini temsil eder.' },
    { flag: '🇩🇪', answer: 'Almanya', wrong: ['Belçika', 'İspanya', 'Avusturya'], fact: 'Siyah-kırmızı-altın renkleri 19. yüzyıldaki birlik hareketinden gelir. Başkenti Berlin\'dir.' },
    { flag: '🇮🇹', answer: 'İtalya', wrong: ['İrlanda', 'Macaristan', 'Meksika'], fact: 'Yeşil-beyaz-kırmızı dikey şeritler. İrlanda ve Meksika bayraklarıyla sık karıştırılır!' },
    { flag: '🇪🇸', answer: 'İspanya', wrong: ['Portekiz', 'İtalya', 'Romanya'], fact: 'Kırmızı-sarı-kırmızı yatay şeritler; ortadaki arma kraliyet sembolüdür. Başkenti Madrid\'dir.' },
    { flag: '🇧🇷', answer: 'Brezilya', wrong: ['Arjantin', 'Portekiz', 'Kolombiya'], fact: 'Yeşil ormanları, sarı eşkenar dörtgen ise madenleri simgeler. Üzerinde "Ordem e Progresso" (Düzen ve İlerleme) yazar.' },
    { flag: '🇺🇸', answer: 'Amerika Birleşik Devletleri', wrong: ['Birleşik Krallık', 'Avustralya', 'Liberya'], fact: '50 yıldız 50 eyaleti, 13 şerit ise kurucu 13 koloniyi temsil eder.' },
    { flag: '🇬🇧', answer: 'Birleşik Krallık', wrong: ['Avustralya', 'Yeni Zelanda', 'Norveç'], fact: '"Union Jack" denir; İngiltere, İskoçya ve İrlanda haçlarının birleşimidir.' },
    { flag: '🇨🇦', answer: 'Kanada', wrong: ['Peru', 'Avusturya', 'Danimarka'], fact: 'Ortadaki akçaağaç yaprağı Kanada\'nın ulusal sembolüdür. Akçaağaç şurubu ile ünlüdür.' },
    { flag: '🇬🇷', answer: 'Yunanistan', wrong: ['İsrail', 'Finlandiya', 'Uruguay'], fact: 'Mavi-beyaz 9 şerit, "Özgürlük ya da Ölüm" sloganının 9 hecesini temsil eder.' },
    { flag: '🇨🇳', answer: 'Çin', wrong: ['Vietnam', 'Kuzey Kore', 'Türkiye'], fact: 'Büyük yıldız Komünist Parti\'yi, dört küçük yıldız halkı temsil eder. Dünyanın en kalabalık 2. ülkesidir.' },
    { flag: '🇰🇷', answer: 'Güney Kore', wrong: ['Japonya', 'Tayland', 'Tayvan'], fact: 'Ortadaki kırmızı-mavi sembol "Taeguk"tur; evrendeki dengeyi (yin-yang) simgeler.' },
    { flag: '🇮🇳', answer: 'Hindistan', wrong: ['İrlanda', 'Nijer', 'Fildişi Sahili'], fact: 'Ortadaki 24 kollu tekerlek "Ashoka Çakrası"dır. Hindistan dünyanın en kalabalık ülkesidir.' },
    { flag: '🇷🇺', answer: 'Rusya', wrong: ['Hollanda', 'Fransa', 'Slovakya'], fact: 'Beyaz-mavi-kırmızı yatay şeritler. Rusya yüzölçümü bakımından dünyanın en büyük ülkesidir.' },
    { flag: '🇦🇷', answer: 'Arjantin', wrong: ['Uruguay', 'Yunanistan', 'Guatemala'], fact: 'Ortadaki "Mayıs Güneşi" 1810 bağımsızlık devrimini simgeler. Tango\'nun anavatanıdır.' },
    { flag: '🇲🇽', answer: 'Meksika', wrong: ['İtalya', 'Macaristan', 'Bulgaristan'], fact: 'Ortadaki arma, yılan yakalayan bir kartaldır — Aztek efsanesine göre başkent bu işaretin görüldüğü yere kuruldu.' },
    { flag: '🇪🇬', answer: 'Mısır', wrong: ['Yemen', 'Suriye', 'Irak'], fact: 'Ortadaki altın kartal "Selahaddin Kartalı"dır. Mısır, piramitleri ve Nil Nehri ile ünlüdür.' },
    { flag: '🇸🇪', answer: 'İsveç', wrong: ['Finlandiya', 'Norveç', 'Ukrayna'], fact: 'Sarı İskandinav haçı mavi zemin üzerindedir. Nobel Ödülleri İsveç\'in başkenti Stokholm\'de verilir.' },
    { flag: '🇳🇴', answer: 'Norveç', wrong: ['İzlanda', 'Danimarka', 'Fransa'], fact: 'Fiyortları ve kuzey ışıkları ile ünlüdür. Bayrağındaki haç tüm İskandinav bayraklarında ortaktır.' },
    { flag: '🇨🇭', answer: 'İsviçre', wrong: ['Danimarka', 'Türkiye', 'Kanada'], fact: 'Dünyada kare şeklinde olan iki bayraktan biridir (diğeri Vatikan). Kızılhaç sembolü bu bayraktan esinlenmiştir.' },
    { flag: '🇳🇱', answer: 'Hollanda', wrong: ['Lüksemburg', 'Rusya', 'Fransa'], fact: 'Dünyanın en eski üç renkli bayrağıdır (1572). Laleler aslında Hollanda\'ya Osmanlı\'dan götürülmüştür!' },
    { flag: '🇵🇹', answer: 'Portekiz', wrong: ['İspanya', 'İtalya', 'Fas'], fact: 'Yeşil umudu, kırmızı denizcilerin kanını simgeler. Portekizliler büyük keşif yolculuklarının öncüsüydü.' },
    { flag: '🇦🇺', answer: 'Avustralya', wrong: ['Yeni Zelanda', 'Birleşik Krallık', 'Fiji'], fact: 'Sağdaki yıldızlar "Güney Haçı" takımyıldızıdır; sadece Güney Yarımküre\'den görülür.' },
    { flag: '🇦🇿', answer: 'Azerbaycan', wrong: ['Türkiye', 'Özbekistan', 'Türkmenistan'], fact: 'Mavi Türklüğü, kırmızı çağdaşlığı, yeşil İslam\'ı temsil eder. Türkiye ile "iki devlet, tek millet" denir.' },
    { flag: '🇺🇦', answer: 'Ukrayna', wrong: ['İsveç', 'Kazakistan', 'Romanya'], fact: 'Mavi gökyüzünü, sarı buğday tarlalarını simgeler. Ukrayna "Avrupa\'nın tahıl ambarı" olarak bilinir.' },
    { flag: '🇵🇱', answer: 'Polonya', wrong: ['Monako', 'Endonezya', 'Çekya'], fact: 'Beyaz-kırmızı. Endonezya ve Monako bayrakları tam tersidir (kırmızı üstte)!' },
    { flag: '🇫🇮', answer: 'Finlandiya', wrong: ['İsveç', 'Yunanistan', 'İzlanda'], fact: 'Mavi haç ülkenin binlerce gölünü ve gökyüzünü simgeler. Finlandiya\'da yaklaşık 188.000 göl vardır!' },
    { flag: '🇩🇰', answer: 'Danimarka', wrong: ['Norveç', 'İsviçre', 'Polonya'], fact: '"Dannebrog" dünyanın hâlâ kullanılan en eski ulusal bayrağı kabul edilir (1219).' },
    { flag: '🇮🇪', answer: 'İrlanda', wrong: ['İtalya', 'Fildişi Sahili', 'Macaristan'], fact: 'Yeşil Katolikleri, turuncu Protestanları, beyaz aradaki barışı simgeler. İtalya bayrağıyla karıştırılır ama İrlanda\'nınki turuncudur.' },
  ],

  // ---------- KATEGORİ 2: ÜNLÜ KİŞİLER ----------
  // "... kimdir?" (4 şıklı)
  unlu: [
    { question: 'Türkiye Cumhuriyeti\'nin kurucusu ve ilk cumhurbaşkanı, "Yurtta sulh, cihanda sulh" sözünün sahibi kimdir?', answer: 'Mustafa Kemal Atatürk', wrong: ['İsmet İnönü', 'Fevzi Çakmak', 'Kâzım Karabekir'], fact: '1881\'de Selanik\'te doğdu. Harf devrimi, kadınlara seçme-seçilme hakkı gibi pek çok yeniliğin öncüsüdür.' },
    { question: 'Görelilik (izafiyet) teorisini geliştiren, E=mc² formülüyle tanınan fizikçi kimdir?', answer: 'Albert Einstein', wrong: ['Isaac Newton', 'Nikola Tesla', 'Stephen Hawking'], fact: '1921 Nobel Fizik Ödülü\'nü görelilik için değil, fotoelektrik etki çalışması için aldı.' },
    { question: 'Mona Lisa ve Son Akşam Yemeği tablolarını yapan; aynı zamanda mucit ve anatomist olan Rönesans dehası kimdir?', answer: 'Leonardo da Vinci', wrong: ['Michelangelo', 'Rafael', 'Vincent van Gogh'], fact: 'Helikopter ve paraşüt benzeri makineleri 500 yıl önce çizmişti. Notlarını ayna yazısıyla (tersten) yazardı.' },
    { question: 'Antik Mısır\'ın son firavunu olan, Sezar ve Antonius ile ittifak kuran ünlü kraliçe kimdir?', answer: 'Kleopatra', wrong: ['Nefertiti', 'Hatşepsut', 'Helen'], fact: 'Aslında Mısırlı değil, Makedon kökenli Ptolemaios hanedanındandı. 9 dil konuştuğu söylenir.' },
    { question: 'Fransa İmparatoru olup Avrupa\'nın büyük bölümünü fetheden, Waterloo Savaşı\'nda yenilen komutan kimdir?', answer: 'Napolyon Bonapart', wrong: ['XIV. Louis', 'Charles de Gaulle', 'Büyük İskender'], fact: 'Sanılanın aksine çok kısa değildi (~1.69 m, dönemine göre ortalama). Çıkardığı medeni kanun bugün hâlâ pek çok ülkeyi etkiler.' },
    { question: '"Gel, gel, ne olursan ol yine gel" çağrısıyla tanınan, Mesnevi\'nin yazarı büyük mutasavvıf kimdir?', answer: 'Mevlânâ Celâleddîn-i Rûmî', wrong: ['Yunus Emre', 'Hacı Bektâş-ı Velî', 'Şems-i Tebrizî'], fact: 'Konya\'da yaşadı. Her yıl aralık ayında Konya\'da anma törenleri (Şeb-i Arus) düzenlenir.' },
    { question: '1453\'te İstanbul\'u fethederek Bizans İmparatorluğu\'na son veren Osmanlı padişahı kimdir?', answer: 'Fatih Sultan Mehmet', wrong: ['Yavuz Sultan Selim', 'Kanuni Sultan Süleyman', 'Osman Gazi'], fact: 'İstanbul\'u fethettiğinde sadece 21 yaşındaydı. Gemileri karadan yürüterek Haliç\'e indirdi.' },
    { question: 'Süleymaniye ve Selimiye camilerini inşa eden, Osmanlı\'nın en büyük başmimarı kimdir?', answer: 'Mimar Sinan', wrong: ['Mimar Kemaleddin', 'Sedefkâr Mehmed Ağa', 'Davud Ağa'], fact: 'Selimiye Camii\'ni "ustalık eserim" olarak tanımladı. 90\'lı yaşlarına kadar 300\'den fazla yapıya imza attı.' },
    { question: 'Radyoaktivite üzerine çalışan, iki farklı dalda Nobel Ödülü kazanan ilk bilim insanı kimdir?', answer: 'Marie Curie', wrong: ['Ada Lovelace', 'Rosalind Franklin', 'Lise Meitner'], fact: 'Polonyum elementine, doğduğu ülke Polonya\'nın adını verdi. Defterleri bugün bile radyoaktiftir!' },
    { question: 'Yerçekimi yasasını ve hareket kanunlarını ortaya koyan, "başına elma düştüğü" anlatılan İngiliz bilim insanı kimdir?', answer: 'Isaac Newton', wrong: ['Galileo Galilei', 'Albert Einstein', 'Charles Darwin'], fact: 'Elma başına düşmedi; ağaçtan düşen elmayı görüp yerçekimini düşündüğü anlatılır. Matematikte kalkülüsü de geliştirdi.' },
    { question: '5 yaşında beste yapmaya başlayan, "Sihirli Flüt" ve "Türk Marşı" ile tanınan Avusturyalı besteci kimdir?', answer: 'Wolfgang Amadeus Mozart', wrong: ['Ludwig van Beethoven', 'Johann Sebastian Bach', 'Frédéric Chopin'], fact: '35 yıllık kısa ömrüne 600\'den fazla eser sığdırdı. "Türk Marşı", Osmanlı mehter müziğinden esinlenmiştir.' },
    { question: 'Kübizm akımının kurucusu olan, "Guernica" tablosuyla savaşın acısını anlatan İspanyol ressam kimdir?', answer: 'Pablo Picasso', wrong: ['Salvador Dalí', 'Claude Monet', 'Henri Matisse'], fact: 'Hayatı boyunca 20.000\'den fazla eser üretti. Tam adı 20\'den fazla kelimeden oluşur!' },
    { question: 'Hamlet, Romeo ve Juliet, Macbeth gibi oyunların yazarı, "olmak ya da olmamak" sözüyle tanınan kimdir?', answer: 'William Shakespeare', wrong: ['Charles Dickens', 'Victor Hugo', 'Lev Tolstoy'], fact: 'İngilizceye 1.700\'den fazla yeni kelime kazandırdığı tahmin edilir. Doğum ve ölüm günü aynı tarihtir: 23 Nisan.' },
    { question: 'Hindistan\'ın bağımsızlık mücadelesini şiddet kullanmadan, pasif direnişle yöneten lider kimdir?', answer: 'Mahatma Gandhi', wrong: ['Nelson Mandela', 'Jawaharlal Nehru', 'Martin Luther King'], fact: '"Mahatma" bir isim değil unvandır; "büyük ruh" anlamına gelir. Tuz Yürüyüşü en ünlü eylemidir.' },
    { question: '1969\'da Ay\'a ayak basan ilk insan kimdir?', answer: 'Neil Armstrong', wrong: ['Buzz Aldrin', 'Yuri Gagarin', 'Michael Collins'], fact: '"Bu, bir insan için küçük ama insanlık için dev bir adımdır" dedi. Uzaya çıkan ilk insan ise Gagarin\'dir (1961).' },
    { question: 'Alternatif akım (AC) sistemini geliştiren, kablosuz enerji üzerine çalışan Sırp asıllı mucit kimdir?', answer: 'Nikola Tesla', wrong: ['Thomas Edison', 'Alexander Graham Bell', 'James Watt'], fact: 'Edison ile yaşadığı rekabete "Akım Savaşları" denir. Manyetik akı yoğunluğu birimi onun adını taşır.' },
    { question: '"Yıldızlı Gece" ve "Ayçiçekleri" tablolarını yapan, yaşarken yalnızca bir tablo satabilen Hollandalı ressam kimdir?', answer: 'Vincent van Gogh', wrong: ['Claude Monet', 'Paul Cézanne', 'Rembrandt'], fact: '10 yılda 2.000\'den fazla eser üretti. Bugün tabloları yüz milyonlarca dolara satılıyor.' },
    { question: 'Duyma yetisini kaybetmesine rağmen 9. Senfoni gibi başyapıtlar besteleyen Alman besteci kimdir?', answer: 'Ludwig van Beethoven', wrong: ['Wolfgang Amadeus Mozart', 'Johannes Brahms', 'Franz Schubert'], fact: '9. Senfoni\'yi tamamen sağırken besteledi. Finalindeki "Neşeye Övgü" bugün Avrupa Birliği\'nin marşıdır.' },
    { question: 'Ampulü ticari olarak kullanılabilir hale getiren, 1.000\'den fazla patenti olan Amerikalı mucit kimdir?', answer: 'Thomas Edison', wrong: ['Nikola Tesla', 'Benjamin Franklin', 'Graham Bell'], fact: '"Dehanın yüzde 1\'i ilham, yüzde 99\'u terdir" sözü ona aittir. Ampulü icat etmedi, kullanışlı hale getirdi.' },
    { question: '"El-Kanun fi\'t-Tıb" adlı tıp ansiklopedisi Avrupa\'da yüzyıllarca ders kitabı olarak okutulan İslam bilgini kimdir?', answer: 'İbn-i Sina', wrong: ['Farabi', 'Biruni', 'Harezmi'], fact: 'Batı\'da "Avicenna" olarak bilinir. Tıp kitabı Avrupa üniversitelerinde 600 yıl boyunca okutuldu.' },
  ],

  // ---------- KATEGORİ 3: DOĞRU / YANLIŞ ----------
  dogruYanlis: [
    { statement: 'Amazon Nehri Arjantin\'den geçer.', answer: false, fact: 'Amazon; Peru, Kolombiya ve Brezilya\'dan geçer. Taşıdığı su miktarı bakımından dünyanın en büyük nehridir.' },
    { statement: 'Türkiye\'nin başkenti İstanbul\'dur.', answer: false, fact: 'Başkent 13 Ekim 1923\'ten beri Ankara\'dır. İstanbul en kalabalık şehir olsa da başkent değildir.' },
    { statement: 'Dünyanın en büyük okyanusu Pasifik (Büyük) Okyanusu\'dur.', answer: true, fact: 'Pasifik, tüm kara parçalarının toplamından daha geniştir ve dünyanın en derin noktası Mariana Çukuru buradadır.' },
    { statement: 'Avustralya hem bir ülke hem de bir kıtadır.', answer: true, fact: 'Avustralya, dünyada tek başına bir kıta kaplayan tek ülkedir.' },
    { statement: 'Everest Dağı Avrupa\'dadır.', answer: false, fact: 'Everest, Asya\'da Himalayalar\'dadır (Nepal-Çin sınırı). Avrupa\'nın en yükseği Elbrus Dağı\'dır.' },
    { statement: 'Rusya dünyanın en kalabalık ülkesidir.', answer: false, fact: 'Rusya yüzölçümü bakımından en büyük ülkedir; en kalabalık ülke ise Hindistan\'dır.' },
    { statement: 'Sahra Çölü Afrika kıtasındadır.', answer: true, fact: 'Sahra, dünyanın en büyük sıcak çölüdür; yaklaşık ABD kadar geniştir.' },
    { statement: 'Japonya\'nın başkenti Pekin\'dir.', answer: false, fact: 'Japonya\'nın başkenti Tokyo\'dur; Pekin, Çin\'in başkentidir.' },
    { statement: 'Işık, sesten daha hızlıdır.', answer: true, fact: 'Bu yüzden şimşeği önce görür, gök gürültüsünü sonra duyarız. Işık saniyede ~300.000 km yol alır.' },
    { statement: 'İnsan vücudundaki en büyük organ kalptir.', answer: false, fact: 'En büyük organ deridir; yetişkin bir insanda yaklaşık 2 m² yüzeye sahiptir.' },
    { statement: 'Penguenler Kuzey Kutbu\'nda yaşar.', answer: false, fact: 'Penguenler Güney Yarımküre\'de (Antarktika ve çevresi) yaşar. Kuzey Kutbu\'nda ise kutup ayıları vardır — ikisi doğada hiç karşılaşmaz!' },
    { statement: 'Mona Lisa tablosunu Picasso yapmıştır.', answer: false, fact: 'Mona Lisa, Leonardo da Vinci\'nin eseridir ve Paris\'teki Louvre Müzesi\'nde sergilenir.' },
    { statement: 'Türkiye\'nin üç tarafı denizlerle çevrilidir.', answer: true, fact: 'Kuzeyde Karadeniz, batıda Ege, güneyde Akdeniz vardır. Marmara ise tamamen sınırlarımız içindeki bir iç denizdir.' },
    { statement: 'Dünya, Güneş etrafındaki turunu yaklaşık 365 günde tamamlar.', answer: true, fact: 'Tam süre 365 gün 6 saattir; bu yüzden 4 yılda bir şubat 29 çeker (artık yıl).' },
    { statement: 'Kanguru, Afrika\'ya özgü bir hayvandır.', answer: false, fact: 'Kangurular Avustralya\'ya özgüdür. Avustralya\'da kanguru sayısı insan sayısından fazladır!' },
    { statement: 'Vatikan, dünyanın en küçük ülkesidir.', answer: true, fact: 'Yüzölçümü yaklaşık 0,44 km²\'dir — bir üniversite kampüsünden bile küçüktür ve Roma\'nın içindedir.' },
    { statement: 'Çin Seddi uzaydan çıplak gözle rahatça görülür.', answer: false, fact: 'Bu yaygın bir şehir efsanesidir; astronotlar çıplak gözle seçilemediğini doğrulamıştır.' },
    { statement: 'İstanbul, iki kıtada yer alan bir şehirdir.', answer: true, fact: 'İstanbul Boğazı, Asya ile Avrupa\'yı ayırır. Dünyada iki kıtaya yayılan az sayıdaki şehirden biridir.' },
    { statement: 'Mısır\'da yalnızca bir piramit vardır.', answer: false, fact: 'Mısır\'da 100\'den fazla piramit bulunur. En ünlüsü Giza\'daki Keops Piramidi, antik dünyanın 7 harikasından ayakta kalan tek yapıdır.' },
    { statement: 'Nil Nehri dünyanın en uzun nehirlerinden biridir.', answer: true, fact: 'Yaklaşık 6.650 km ile Amazon\'la birlikte "en uzun nehir" unvanı için yarışır ve 11 ülkeden geçer.' },
  ],

  // ---------- KATEGORİ: BAŞKENTLER ----------
  // "... ülkesinin başkenti neresidir?" (4 şıklı)
  baskent: [
    { question: 'Fransa\'nın başkenti neresidir?', answer: 'Paris', wrong: ['Lyon', 'Marsilya', 'Nice'], fact: 'Eyfel Kulesi 1889 Dünya Fuarı için geçiciydi — yıkılması planlanıyordu ama radyo anteni olarak işe yarayınca kaldı.' },
    { question: 'Almanya\'nın başkenti neresidir?', answer: 'Berlin', wrong: ['Münih', 'Hamburg', 'Frankfurt'], fact: 'Berlin Duvarı şehri 28 yıl ikiye böldü ve 1989\'da yıkıldı.' },
    { question: 'İtalya\'nın başkenti neresidir?', answer: 'Roma', wrong: ['Milano', 'Venedik', 'Napoli'], fact: 'Dünyanın en küçük ülkesi Vatikan, Roma\'nın tam ortasındadır — şehir içinde ülke!' },
    { question: 'İspanya\'nın başkenti neresidir?', answer: 'Madrid', wrong: ['Barselona', 'Sevilla', 'Valensiya'], fact: 'Madrid, yaklaşık 667 metre rakımıyla Avrupa\'nın en yüksek başkentlerinden biridir.' },
    { question: 'Birleşik Krallık\'ın (İngiltere) başkenti neresidir?', answer: 'Londra', wrong: ['Manchester', 'Liverpool', 'Edinburgh'], fact: '"Big Ben" aslında kulenin değil, içindeki 13,7 tonluk çanın adıdır; kulenin adı Elizabeth Kulesi\'dir.' },
    { question: 'Japonya\'nın başkenti neresidir?', answer: 'Tokyo', wrong: ['Osaka', 'Kyoto', 'Hiroşima'], fact: 'Tokyo metropol bölgesi ~37 milyon kişiyle dünyanın en kalabalık şehir bölgesidir. Eski başkent ise Kyoto\'ydu.' },
    { question: 'Çin\'in başkenti neresidir?', answer: 'Pekin', wrong: ['Şanghay', 'Hong Kong', 'Guangzhou'], fact: 'Şanghay daha kalabalık olsa da başkent Pekin\'dir. Pekin\'deki Yasak Şehir, 500 yıl boyunca halka kapalıydı.' },
    { question: 'Rusya\'nın başkenti neresidir?', answer: 'Moskova', wrong: ['St. Petersburg', 'Kazan', 'Soçi'], fact: 'St. Petersburg yaklaşık 200 yıl Rusya\'nın başkentiydi; 1918\'de başkent yeniden Moskova oldu.' },
    { question: 'Amerika Birleşik Devletleri\'nin başkenti neresidir?', answer: 'Washington D.C.', wrong: ['New York', 'Los Angeles', 'Chicago'], fact: 'En kalabalık şehir New York\'tur ama başkent Washington D.C.\'dir — D.C. hiçbir eyalete bağlı değildir.' },
    { question: 'Kanada\'nın başkenti neresidir?', answer: 'Ottawa', wrong: ['Toronto', 'Vancouver', 'Montreal'], fact: 'Çoğu kişi Toronto sanır ama başkent Ottawa\'dır. Kışın donmuş Rideau Kanalı dev bir buz pateni pistine dönüşür.' },
    { question: 'Avustralya\'nın başkenti neresidir?', answer: 'Kanberra', wrong: ['Sidney', 'Melbourne', 'Brisbane'], fact: 'Sidney ile Melbourne başkentlik için yarışınca, ikisinin ortasına sıfırdan Kanberra kuruldu (1913).' },
    { question: 'Türkiye\'nin başkenti neresidir?', answer: 'Ankara', wrong: ['İstanbul', 'İzmir', 'Bursa'], fact: 'Ankara, Kurtuluş Savaşı\'nın yönetildiği merkez olduğu için 13 Ekim 1923\'te başkent ilan edildi.' },
    { question: 'Yunanistan\'ın başkenti neresidir?', answer: 'Atina', wrong: ['Selanik', 'Patra', 'Larisa'], fact: 'Atina, adını bilgelik tanrıçası Athena\'dan alır ve demokrasinin doğduğu şehir kabul edilir.' },
    { question: 'Mısır\'ın başkenti neresidir?', answer: 'Kahire', wrong: ['İskenderiye', 'Luksor', 'Giza'], fact: 'Ünlü piramitler Kahire\'nin hemen bitişiğindeki Giza\'dadır — şehirden piramitler görülebilir.' },
    { question: 'Brezilya\'nın başkenti neresidir?', answer: 'Brasília', wrong: ['Rio de Janeiro', 'São Paulo', 'Salvador'], fact: 'Başkent Rio değildir! Brasília 1960\'ta sıfırdan planlanarak kuruldu; kuşbakışı bir uçağa benzer.' },
    { question: 'Arjantin\'in başkenti neresidir?', answer: 'Buenos Aires', wrong: ['Kordoba', 'Rosario', 'Mendoza'], fact: '"Buenos Aires" İspanyolca "güzel havalar" anlamına gelir.' },
    { question: 'Hollanda\'nın başkenti neresidir?', answer: 'Amsterdam', wrong: ['Rotterdam', 'Lahey', 'Utrecht'], fact: 'Resmi başkent Amsterdam\'dır ama hükümet ve parlamento Lahey\'dedir. Amsterdam\'da 165\'ten fazla kanal vardır.' },
    { question: 'Portekiz\'in başkenti neresidir?', answer: 'Lizbon', wrong: ['Porto', 'Faro', 'Braga'], fact: 'Lizbon, Avrupa\'nın en eski başkentlerinden biridir — Roma\'dan ve Londra\'dan bile eskidir.' },
    { question: 'Güney Kore\'nin başkenti neresidir?', answer: 'Seul', wrong: ['Busan', 'Incheon', 'Daegu'], fact: 'Güney Kore nüfusunun neredeyse yarısı Seul metropol bölgesinde yaşar.' },
    { question: 'Azerbaycan\'ın başkenti neresidir?', answer: 'Bakü', wrong: ['Gence', 'Sumgayıt', 'Şuşa'], fact: 'Bakü, deniz seviyesinin ~28 metre altında yer alan dünyanın en alçak rakımlı başkentidir.' },
  ],

  // ---------- KATEGORİ: HANGİ KITADA? ----------
  // "... hangi kıtadadır?" (4 şıklı)
  kita: [
    { question: 'Brezilya hangi kıtadadır?', answer: 'Güney Amerika', wrong: ['Kuzey Amerika', 'Afrika', 'Avrupa'], fact: 'Brezilya, Güney Amerika\'nın neredeyse yarısını kaplar ve Amazon yağmur ormanlarının büyük bölümü buradadır.' },
    { question: 'Mısır hangi kıtadadır?', answer: 'Afrika', wrong: ['Asya', 'Avrupa', 'Okyanusya'], fact: 'İlginç detay: Mısır\'ın Sina Yarımadası aslında Asya\'dadır — yani Mısır teknik olarak iki kıtaya yayılır.' },
    { question: 'Japonya hangi kıtadadır?', answer: 'Asya', wrong: ['Okyanusya', 'Avrupa', 'Kuzey Amerika'], fact: 'Japonya yaklaşık 6.800 adadan oluşan bir takımada ülkesidir.' },
    { question: 'Almanya hangi kıtadadır?', answer: 'Avrupa', wrong: ['Asya', 'Kuzey Amerika', 'Afrika'], fact: 'Almanya\'nın 9 komşusu vardır — Avrupa\'da en çok komşuya sahip ülkelerden biridir.' },
    { question: 'Meksika hangi kıtadadır?', answer: 'Kuzey Amerika', wrong: ['Güney Amerika', 'Avrupa', 'Afrika'], fact: 'Meksika, Güney Amerika sanılır ama coğrafi olarak Kuzey Amerika kıtasındadır.' },
    { question: 'Kenya hangi kıtadadır?', answer: 'Afrika', wrong: ['Asya', 'Güney Amerika', 'Okyanusya'], fact: 'Ekvator çizgisi Kenya\'nın tam ortasından geçer. Safari turlarının en ünlü adreslerindendir.' },
    { question: 'Hindistan hangi kıtadadır?', answer: 'Asya', wrong: ['Afrika', 'Avrupa', 'Okyanusya'], fact: 'Hindistan o kadar büyüktür ki kendi başına "alt kıta" olarak anılır.' },
    { question: 'Arjantin hangi kıtadadır?', answer: 'Güney Amerika', wrong: ['Kuzey Amerika', 'Avrupa', 'Afrika'], fact: 'Arjantin\'in güneyindeki Patagonya, Antarktika\'ya en yakın yerleşim bölgelerindendir.' },
    { question: 'Kanada hangi kıtadadır?', answer: 'Kuzey Amerika', wrong: ['Avrupa', 'Asya', 'Güney Amerika'], fact: 'Kanada, Rusya\'dan sonra dünyanın en büyük 2. ülkesidir ve dünyadaki göllerin çoğu buradadır.' },
    { question: 'Nijerya hangi kıtadadır?', answer: 'Afrika', wrong: ['Güney Amerika', 'Asya', 'Okyanusya'], fact: 'Nijerya, 200 milyonu aşan nüfusuyla Afrika\'nın en kalabalık ülkesidir.' },
    { question: 'Vietnam hangi kıtadadır?', answer: 'Asya', wrong: ['Afrika', 'Okyanusya', 'Güney Amerika'], fact: 'Vietnam, dünyanın en büyük kahve üreticilerinden biridir — Brezilya\'dan sonra ikinci sırada.' },
    { question: 'Norveç hangi kıtadadır?', answer: 'Avrupa', wrong: ['Kuzey Amerika', 'Asya', 'Okyanusya'], fact: 'Norveç\'in kuzeyinde yazın güneş hiç batmaz — buna "gece yarısı güneşi" denir.' },
    { question: 'Peru hangi kıtadadır?', answer: 'Güney Amerika', wrong: ['Afrika', 'Asya', 'Kuzey Amerika'], fact: 'İnka İmparatorluğu\'nun kayıp şehri Machu Picchu, Peru\'nun And Dağları\'ndadır.' },
    { question: 'Fas hangi kıtadadır?', answer: 'Afrika', wrong: ['Avrupa', 'Asya', 'Güney Amerika'], fact: 'Fas ile İspanya arasındaki Cebelitarık Boğazı sadece 14 km\'dir — Afrika\'dan Avrupa görülebilir!' },
    { question: 'Tayland hangi kıtadadır?', answer: 'Asya', wrong: ['Okyanusya', 'Afrika', 'Avrupa'], fact: 'Tayland, Güneydoğu Asya\'da hiçbir zaman sömürge olmamış tek ülkedir.' },
    { question: 'Yeni Zelanda hangi kıtadadır?', answer: 'Okyanusya', wrong: ['Asya', 'Avrupa', 'Güney Amerika'], fact: 'Yeni Zelanda, Avustralya\'nın parçası değildir — aralarında ~2.000 km okyanus vardır. Sembolü kivi kuşudur.' },
  ],

  // ---------- KATEGORİ: HANGİSİ DAHA ESKİ? ----------
  // İki olaydan hangisi daha önce oldu? (yıl negatifse MÖ)
  eski: [
    { a: { text: 'İstanbul\'un Fethi', year: 1453 }, b: { text: 'Amerika\'nın Keşfi', year: 1492 }, fact: 'Fetih (1453), Kolomb\'un yolculuğundan (1492) 39 yıl öncedir. Hatta bazı tarihçilere göre fetih, yeni ticaret yolu arayışını tetikledi.' },
    { a: { text: 'Giza Piramitleri\'nin inşası', year: -2560 }, b: { text: 'Roma şehrinin kuruluşu', year: -753 }, fact: 'Piramitler (MÖ ~2560), Roma\'nın kuruluşundan (MÖ 753) yaklaşık 1.800 yıl daha eskidir. Piramitler, Kleopatra\'ya bizden daha uzaktır!' },
    { a: { text: 'İlk elektronik bilgisayar (ENIAC)', year: 1945 }, b: { text: 'Ay\'a ilk ayak basış', year: 1969 }, fact: 'ENIAC (1945) 27 ton ağırlığındaydı. 24 yıl sonra Ay\'a giden Apollo bilgisayarı, bugünkü hesap makinelerinden bile basitti.' },
    { a: { text: 'Cumhuriyet\'in ilanı', year: 1923 }, b: { text: 'İkinci Dünya Savaşı\'nın başlaması', year: 1939 }, fact: 'Cumhuriyet 29 Ekim 1923\'te ilan edildi; İkinci Dünya Savaşı 16 yıl sonra, 1939\'da başladı. Türkiye savaşa fiilen girmedi.' },
    { a: { text: 'Amerikan Bağımsızlık Bildirgesi', year: 1776 }, b: { text: 'Fransız Devrimi', year: 1789 }, fact: 'Amerikan bağımsızlığı (1776), Fransız Devrimi\'nden (1789) 13 yıl öncedir ve ona ilham kaynağı olmuştur.' },
    { a: { text: 'Matbaanın icadı (Gutenberg)', year: 1440 }, b: { text: 'Telefonun icadı (Bell)', year: 1876 }, fact: 'Aralarında 436 yıl var! Gutenberg\'in matbaası bilginin yayılmasını sağlayarak Rönesans\'ı hızlandırdı.' },
    { a: { text: 'Titanik\'in batışı', year: 1912 }, b: { text: 'Birinci Dünya Savaşı\'nın başlaması', year: 1914 }, fact: 'Titanik 1912\'de battı; sadece 2 yıl sonra Birinci Dünya Savaşı başladı ve Titanik\'in kardeş gemisi Britannic savaşta hastane gemisi olarak görev yaptı.' },
    { a: { text: 'Berlin Duvarı\'nın yıkılışı', year: 1989 }, b: { text: 'World Wide Web\'in halka açılması', year: 1991 }, fact: 'Duvar 1989\'da yıkıldı; Web 1991\'de halka açıldı. İkisi de dünyayı "birleştiren" olaylar olarak anılır.' },
    { a: { text: 'Magna Carta\'nın imzalanması', year: 1215 }, b: { text: 'Osmanlı Devleti\'nin kuruluşu', year: 1299 }, fact: 'İngiltere\'de kralın yetkilerini sınırlayan Magna Carta (1215), Osmanlı\'nın kuruluşundan (1299) 84 yıl öncedir.' },
    { a: { text: 'İlk otomobil (Benz)', year: 1886 }, b: { text: 'İlk motorlu uçuş (Wright kardeşler)', year: 1903 }, fact: 'İlk araba (1886) ile ilk uçak (1903) arasında sadece 17 yıl var. 66 yıl sonra ise insan Ay\'daydı!' },
    { a: { text: 'Radyonun icadı', year: 1895 }, b: { text: 'Televizyonun icadı', year: 1927 }, fact: 'Radyo (1895) televizyondan (1927) 32 yıl önce geldi. İlk TV yayınları hareketli siluetlerden ibaretti.' },
    { a: { text: 'Mona Lisa\'nın yapılması', year: 1503 }, b: { text: 'Süleymaniye Camii\'nin tamamlanması', year: 1557 }, fact: 'Da Vinci Mona Lisa\'ya 1503\'te başladı; Mimar Sinan Süleymaniye\'yi 1557\'de bitirdi. İki usta neredeyse çağdaştı.' },
    { a: { text: 'Antik Olimpiyat Oyunları\'nın başlaması', year: -776 }, b: { text: 'Büyük İskender\'in doğumu', year: -356 }, fact: 'İlk Olimpiyatlar (MÖ 776), Büyük İskender\'den (MÖ 356) 420 yıl öncedir. Modern olimpiyatlar ise 1896\'da yeniden başladı.' },
    { a: { text: 'Darwin\'in "Türlerin Kökeni" kitabı', year: 1859 }, b: { text: 'Einstein\'ın görelilik teorisi', year: 1905 }, fact: 'Darwin (1859) ile Einstein (1905) arasında 46 yıl var — ikisi de kendi alanında bilimi kökten değiştirdi.' },
  ],

  // ---------- KATEGORİ 4: YAZ BAKALIM (DÜELLO) ----------
  // İki oyuncu sırayla cevap yazar; yazamayan / yanlış yazan kaybeder.
  // aliases: kabul edilen alternatif yazımlar (normalize edilmiş halleriyle eşleşir)
  duello: [
    {
      prompt: 'A ile başlayan Avrupa ülkelerini yazın.',
      answers: [
        { name: 'Almanya', aliases: ['germany'] },
        { name: 'Andorra', aliases: [] },
        { name: 'Arnavutluk', aliases: ['albania'] },
        { name: 'Avusturya', aliases: ['austria'] },
        { name: 'Azerbaycan', aliases: ['azerbaijan'] },
      ],
      note: 'Azerbaycan\'ın topraklarının bir kısmı Avrupa\'da sayıldığı için kabul ediliyor.',
    },
    {
      prompt: 'Türkiye\'ye kara sınırı olan komşu ülkeleri yazın.',
      answers: [
        { name: 'Yunanistan', aliases: [] },
        { name: 'Bulgaristan', aliases: [] },
        { name: 'Gürcistan', aliases: [] },
        { name: 'Ermenistan', aliases: [] },
        { name: 'Azerbaycan', aliases: ['nahcivan', 'nahçıvan'] },
        { name: 'İran', aliases: [] },
        { name: 'Irak', aliases: [] },
        { name: 'Suriye', aliases: [] },
      ],
      note: 'Azerbaycan ile sınırımız, Nahçıvan özerk bölgesi üzerindendir (sadece ~17 km!).',
    },
    {
      prompt: 'Güneş Sistemi\'ndeki gezegenleri yazın.',
      answers: [
        { name: 'Merkür', aliases: [] },
        { name: 'Venüs', aliases: [] },
        { name: 'Dünya', aliases: [] },
        { name: 'Mars', aliases: [] },
        { name: 'Jüpiter', aliases: [] },
        { name: 'Satürn', aliases: [] },
        { name: 'Uranüs', aliases: [] },
        { name: 'Neptün', aliases: [] },
      ],
      note: 'Plüton 2006\'da "cüce gezegen" sınıfına alındığı için artık sayılmıyor.',
    },
    {
      prompt: 'Güney Amerika ülkelerini yazın.',
      answers: [
        { name: 'Brezilya', aliases: ['brazil'] },
        { name: 'Arjantin', aliases: [] },
        { name: 'Şili', aliases: ['chile'] },
        { name: 'Peru', aliases: [] },
        { name: 'Kolombiya', aliases: ['colombia'] },
        { name: 'Venezuela', aliases: ['venezuella'] },
        { name: 'Ekvador', aliases: ['ekvator', 'ecuador'] },
        { name: 'Bolivya', aliases: [] },
        { name: 'Paraguay', aliases: [] },
        { name: 'Uruguay', aliases: [] },
        { name: 'Guyana', aliases: [] },
        { name: 'Surinam', aliases: ['suriname'] },
      ],
      note: 'Brezilya tek başına kıtanın neredeyse yarısını kaplar.',
    },
    {
      prompt: 'İ ile başlayan ülkeleri yazın.',
      answers: [
        { name: 'İtalya', aliases: [] },
        { name: 'İspanya', aliases: [] },
        { name: 'İsveç', aliases: [] },
        { name: 'İsviçre', aliases: [] },
        { name: 'İrlanda', aliases: [] },
        { name: 'İzlanda', aliases: [] },
        { name: 'İran', aliases: [] },
        { name: 'İsrail', aliases: [] },
        { name: 'İngiltere', aliases: ['birlesik krallik', 'birleşik krallık'] },
      ],
      note: 'İngiltere\'nin resmi adı Birleşik Krallık\'tır ama Türkçede İngiltere yaygın kullanımdır.',
    },
    {
      prompt: 'Dünyadaki kıtaları yazın.',
      answers: [
        { name: 'Asya', aliases: [] },
        { name: 'Afrika', aliases: [] },
        { name: 'Avrupa', aliases: [] },
        { name: 'Kuzey Amerika', aliases: [] },
        { name: 'Güney Amerika', aliases: [] },
        { name: 'Antarktika', aliases: ['antartika'] },
        { name: 'Avustralya (Okyanusya)', aliases: ['avustralya', 'avusturalya', 'okyanusya'] },
      ],
      note: 'Asya, hem yüzölçümü hem nüfus olarak en büyük kıtadır.',
    },
    {
      prompt: 'Marmara Bölgesi\'ndeki illeri yazın.',
      answers: [
        { name: 'İstanbul', aliases: [] },
        { name: 'Bursa', aliases: [] },
        { name: 'Kocaeli', aliases: ['izmit'] },
        { name: 'Sakarya', aliases: ['adapazari', 'adapazarı'] },
        { name: 'Balıkesir', aliases: [] },
        { name: 'Çanakkale', aliases: [] },
        { name: 'Edirne', aliases: [] },
        { name: 'Kırklareli', aliases: [] },
        { name: 'Tekirdağ', aliases: [] },
        { name: 'Yalova', aliases: [] },
        { name: 'Bilecik', aliases: [] },
      ],
      note: 'Marmara, Türkiye\'nin en kalabalık ve en sanayileşmiş bölgesidir.',
    },
    {
      prompt: 'Nüfusu 100 milyonu aşan ülkeleri yazın.',
      answers: [
        { name: 'Çin', aliases: ['cin'] },
        { name: 'Hindistan', aliases: [] },
        { name: 'ABD', aliases: ['amerika', 'amerika birlesik devletleri', 'amerika birleşik devletleri', 'usa'] },
        { name: 'Endonezya', aliases: [] },
        { name: 'Pakistan', aliases: [] },
        { name: 'Nijerya', aliases: [] },
        { name: 'Brezilya', aliases: ['brazil'] },
        { name: 'Bangladeş', aliases: ['banglades'] },
        { name: 'Rusya', aliases: [] },
        { name: 'Meksika', aliases: [] },
        { name: 'Etiyopya', aliases: [] },
        { name: 'Japonya', aliases: [] },
        { name: 'Filipinler', aliases: [] },
        { name: 'Mısır', aliases: ['misir'] },
        { name: 'Vietnam', aliases: ['viyetnam'] },
        { name: 'Demokratik Kongo Cumhuriyeti', aliases: ['kongo', 'dr kongo', 'kongo dc'] },
      ],
      note: 'Türkiye yaklaşık 85 milyonla bu listenin biraz dışında kalıyor.',
    },
  ],
};

const CATEGORIES = {
  bayrak:      { name: 'Bayraklar',          icon: '🚩', desc: 'Bu bayrak hangi ülkenin?' },
  unlu:        { name: 'Ünlü Kişiler',       icon: '🎭', desc: 'Bu ünlü kişi kim?' },
  dogruYanlis: { name: 'Doğru / Yanlış',     icon: '⚖️', desc: 'Bu bilgi doğru mu?' },
  baskent:     { name: 'Başkentler',         icon: '🏛️', desc: 'Bu ülkenin başkenti neresi?' },
  kita:        { name: 'Hangi Kıtada?',      icon: '🗺️', desc: 'Bu ülke hangi kıtada?' },
  eski:        { name: 'Hangisi Daha Eski?', icon: '⏳', desc: 'Hangisi daha önce oldu?' },
  duello:      { name: 'Yaz Bakalım',        icon: '⚔️', desc: 'Sırayla yazın, yazamayan kaybeder!' },
};
